

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST'
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS'
export const FETCH_ALBUM_FAILURE = 'FETCH_ALBUM_FAILURE'



export const TRACK_STATE_PLAYING = 'TRACK_STATE_PLAYING'
export const TRACK_STATE_STOPPED = 'TRACK_STATE_STOPPED'
export const TRACK_STATE_PAUSED = 'TRACK_STATE_PAUSED'

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST'
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS'
export const FETCH_ARTIST_FAILURE = 'FETCH_ARTIST_FAILURE'

export const FETCH_RECENTLY_ARTIST_REQUEST = 'FETCH_RECENTLY_ARTIST_REQUEST'
export const FETCH_RECENTLY_ARTIST_SUCCESS = 'FETCH_RECENTLY_ARTIST_SUCCESS'
export const FETCH_RECENTLY_ARTIST_FAILURE = 'FETCH_RECENTLY_ARTIST_FAILURE'


export const SET_ARTIST_IDS = 'SET_ARTIST_IDS'

export const SET_RECENTLY_PLAYED_ARTISTS = 'SET_RECENTLY_PLAYED_ARTISTS'


export const FETCH_CATEGORIES_REQUEST = 'FETCH_CATEGORIES_REQUEST'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_FAILURE = 'FETCH_CATEGORIES_FAILURE'

export const FETCH_NEW_RELEASES_REQUEST = 'FETCH_NEW_RELEASES_REQUEST'
export const FETCH_NEW_RELEASES_SUCCESS = 'FETCH_NEW_RELEASES_SUCCESS'
export const FETCH_NEW_RELEASES_FAILURE = 'FETCH_NEW_RELEASES_FAILURE'

export const FETCH_FEATURED_REQUEST = 'FETCH_FEATURED_REQUEST'
export const FETCH_FEATURED_SUCCESS = 'FETCH_FEATURED_SUCCESS'
export const FETCH_FEATURED_FAILURE = 'FETCH_FEATURED_FAILURE'


export const FETCH_PLAYLIST_MENU_REQUEST = 'FETCH_PLAYLIST_MENU_REQUEST'
export const FETCH_PLAYLIST_MENU_SUCCESS = 'FETCH_PLAYLIST_MENU_SUCCESS'
export const FETCH_PLAYLIST_MENU_FAILURE = 'FETCH_PLAYLIST_MENU_FAILURE'

export const ADD_PLAYLIST_ITEM = 'ADD_PLAYLIST_ITEM'

export const UPDATE_VIEW_TYPE = 'UPDATE_VIEW_TYPE'
export const UPDATE_LIBRARY_VIEW = 'UPDATE_LIBRARY_VIEW'

export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST'
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS'
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE'

export const SEARCH_SONGS_REQUEST = 'SEARCH_SONGS_REQUEST'
export const SEARCH_SONGS_SUCCESS = 'SEARCH_SONGS_SUCCESS'
export const SEARCH_SONGS_FAILURE = 'SEARCH_SONGS_FAILURE'


export const FETCH_ARTIST_SONGS_REQUEST = 'FETCH_ARTIST_SONGS_REQUEST'
export const FETCH_ARTIST_SONGS_SUCCESS = 'FETCH_ARTIST_SONGS_SUCCESS'
export const FETCH_ARTIST_SONGS_FAILURE = 'FETCH_ARTIST_SONGS_FAILURE'

export const FETCH_RECENTLY_PLAYED_REQUEST = 'FETCH_RECENTLY_PLAYED_REQUEST'
export const FETCH_RECENTLY_PLAYED_SUCCESS = 'FETCH_RECENTLY_PLAYED_SUCCESS'
export const FETCH_RECENTLY_PLAYED_FAILURE = 'FETCH_RECENTLY_PLAYED_FAILURE'

export const FETCH_PLAYLIST_SONGS_REQUEST = 'FETCH_PLAYLIST_SONGS_REQUEST'
export const FETCH_PLAYLIST_SONGS_SUCCESS = 'FETCH_PLAYLIST_SONGS_SUCCESS'
export const FETCH_PLAYLIST_SONGS_FAILURE = 'FETCH_PLAYLIST_SONGS_FAILURE'

export const PLAY_SONG = 'PLAY_SONG'
export const STOP_SONG = 'STOP_SONG'
export const PAUSE_SONG = 'PAUSE_SONG'
export const RESUME_SONG = 'RESUME_SONG'
export const INCREASE_SONG_TIME = 'INCREASE_SONG_TIME'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'

export const CREATE_PLAYLIST_REQUEST = 'CREATE_PLAYLIST_REQUEST'
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS'
export const CREATE_PLAYLIST_FAILURE = 'CREATE_PLAYLIST_FAILURE'

export const UPDATE_VOLUME = 'UPDATE_VOLUME'

export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE'

export const SET_TOKEN = 'SET_TOKEN'

export const ADD_SONG_TO_LIBRARY_REQUEST = 'ADD_SONG_TO_LIBRARY_REQUEST'
export const ADD_SONG_TO_LIBRARY_SUCCESS = 'ADD_SONG_TO_LIBRARY_SUCCESS'
export const ADD_SONG_TO_LIBRARY_FAILURE = 'ADD_SONG_TO_LIBRARY_FAILURE'





