

export const FETCH_ALBUM_REQUEST = 'FETCH_ALBUM_REQUEST'
export const FETCH_ALBUM_SUCCESS = 'FETCH_ALBUM_SUCCESS'
export const FETCH_ALBUM_FAILURE = 'FETCH_ALBUM_FAILURE'

export const FETCH_ARTIST_REQUEST = 'FETCH_ARTIST_REQUEST'
export const FETCH_ARTIST_SUCCESS = 'FETCH_ARTIST_SUCCESS'
export const FETCH_ARTIST_FAILURE = 'FETCH_ARTIST_FAILURE'


export const FETCH_CATEGORY_REQUEST = 'FETCH_CATEGORY_REQUEST'
export const FETCH_CATEGORY_SUCCESS = 'FETCH_CATEGORY_SUCCESS'
export const FETCH_CATEGORY_FAILURE = 'FETCH_CATEGORY_FAILURE'


export const FETCH_PLAYLIST_REQUEST = 'FETCH_PLAYLIST_REQUEST'
export const FETCH_PLAYLIST_SUCCESS = 'FETCH_PLAYLIST_SUCCESS'
export const FETCH_PLAYLIST_FAILURE = 'FETCH_PLAYLIST_FAILURE'


export const FETCH_SONGS_REQUEST = 'FETCH_SONGS_REQUEST'
export const FETCH_SONGS_SUCCESS = 'FETCH_SONGS_SUCCESS'
export const FETCH_SONGS_FAILURE = 'FETCH_SONGS_FAILURE'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'


export const UPDATE_VOLUME = 'UPDATE_VOLUME'

export const UPDATE_HEADER_TITLE = 'UPDATE_HEADER_TITLE'

export const SET_TOKEN = 'SET_TOKEN'






